name: kalori
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter:
    sdk: flutter
  animations: ^2.0.11
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7

  cupertino_icons: ^1.0.8

  # Firebase bağımlılıkları
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.7
  shared_preferences: ^2.0.15
  firebase_data_connect: ^0.1.0

  path_provider: ^2.0.13
  tflite_flutter: ^0.11.0
  image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/icons/empty_plate.svg
    - assets/icons/default_profile.jpg
    - assets/ai_model/
    - assets/ai_model/model_gender_q.tflite
    - assets/ai_model/model_age_q.tflite

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  remove_alpha_ios: true
